spring.application.name=api-gateway
server.port=8000
eureka.client.service-url.defaultZone=http://localhost:9000/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance-id:${random.value}}

spring.cloud.gateway.mvc.routes[0].id=user-service
spring.cloud.gateway.mvc.routes[0].uri=lb://user-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/user/**

jwt.secret=Ws0jpeml0LjWj1I3oVZPNQ636V+Thr++n9iShSLnLn8=

logging.level.org.springframework.security=DEBUG

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer