spring.application.name=api-gateway
server.port=8000
eureka.client.service-url.defaultZone=http://localhost:9000/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance-id:${random.value}}

spring.cloud.gateway.mvc.routes[0].id=user-service
spring.cloud.gateway.mvc.routes[0].uri=lb://user-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/user/**
